- name: Copy Files
  copy:
    dest: "{{ ansibleHome }}/{{ item }}"
    src: "{{ role_path }}/../ansible/files/{{ item }}"
  loop: "{{ ansibleFiles }}"

- name: Change ssh key permissions
  file:
    mode: '600'
    path: "{{ ansibleHome }}/aws"

- name: Enable Needed Repos
  yum:
    update_cache: yes
    name:
      - centos-release-scl
      - epel-release
    state: present
  become: yes

- name: Install Packages
  yum:
    update_cache: yes
    name: "{{ ansiblePackages }}"
    state: present
  become: yes

- name: Clone openshift-ansible Repo
  git:
    #accept_hostkey: yes
    depth: 1
    repo: "{{ ansibleRepoUrl }}"
    dest: "{{ ansibleHome }}/openshift-ansible"
    version: "{{ openshiftRelease }}"

- name: Python Packages Install 
  pip:
    executable: "{{ pythonInstallPath }}/pip"
    requirements: "{{ ansibleHome }}/requirements.txt"
  become: yes

- name: Create Symbolic Links 
  file:
    state: link
    src: "{{ pythonInstallPath }}/{{ item }}"
    dest: "/usr/bin/{{ item }}"
  loop: "{{ softLinks }}"
  become: yes


