---

okdCidrBlock: 10.0.0.0/16
www: 0.0.0.0/0
ignition: "{{ playbook_dir }}/ignition"
metadataFile: "{{ ignition }}/metadata.json"
clusterID: "{{ (lookup('file', metadataFile )|from_json).get('infraID') }}"
