---
- name: Create OpenShift "{{ item.type }}" nodes
  ec2:
    key_name: "{{ sshKey }}"
    groups: "{{ groupName }}"
    assign_public_ip: yes
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    exact_count: "{{ item.count }}"
    count_tag:
      node: "{{ item.type }}"
    instance_tags:
      node: "{{ item.type }}"
    image: "{{ awsImage }}"
    instance_type: "{{ item.size }}"
    region: "{{ awsRegion }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ item.volumeSize }}"
        delete_on_termination: "{{ item.volumeDelete }}"
    wait: "{{ item.createWait }}"
  #  when: item.count > 0
