---

- name: Get "{{ instanceState }}" instances
  ec2_instance_info:
    region: "{{ awsRegion }}"
    filters:
      instance-state-name: [ "{{ instanceState }}" ]
      cluster: "{{ clusterID }}"
  register: list
