- name: Get Worker Nodes
  ec2_instance_info:
    region: "{{ awsRegion }}"
    filters:
      instance-state-name: [ "running" ]
      "tag:node": worker
  register: instances

- name: Get Master Nodes
  ec2_instance_info:
    region: "{{ awsRegion }}"
    filters:
      instance-state-name: [ "running" ]
      "tag:node": master
  register: masters

- name: Generate OpenShift Inventory File
  local_action:
    module: template
    src: "{{ role_path }}/templates/openshift.j2"
    dest: "{{ role_path }}/files/openshift.gen"

- name: Get Standalone Registry Nodes
  ec2_instance_info:
    region: "{{ awsRegion }}"
    filters:
      instance-state-name: [ "running" ]
      "tag:node": registry
  register: registry

- name: Generate Registry Inventory File
  local_action:
    module: template
    src: "{{ role_path }}/templates/registry.j2"
    dest: "{{ role_path }}/files/registry.gen"

- name: Get Ansible Node
  ec2_instance_info:
    region: "{{ awsRegion }}"
    filters:
      instance-state-name: [ "running" ]
      "tag:node": ansible
  register: ansible

- name: Generate Public IP Inventory File
  local_action:
    module: template
    src: "{{ role_path }}/templates/nodes_public_ip.j2"
    dest: "{{ role_path }}/files/public_nodes.gen"

# register: result
# until: result.rc != 255
# retries: 10
# delay: 60
